# Generated by Django 5.1.3 on 2024-12-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('course_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=128)),
                ('t_name', models.CharField(max_length=128)),
            ],
        ),
    ]
